# Generated by Django 3.1.3 on 2020-12-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_contactformmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
