# Generated by Django 3.1.3 on 2020-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_delete_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
